import Clientonly from "./components/Clientonly";
import Modal from "./components/modals/Modal";
import RegisterModel from "./components/modals/RegisterModel";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

const font = useInt

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Clientonly>
          <Navbar />
          <RegisterModel />
        </Clientonly>
        {children}
      </body>
    </html>
  );
}
